### ISSUE TITLE
Documentation lacks requirements

### ISSUE THREAD

**Issue by ToeiRei** [gaillota/UrlShortener#1]
No dependencies or requirements listed...

**Comment by gaillota** [comment]
Unless I don't understand your meaning of dependencies, the dependencies are listed in the `composer.json` file.
As for the requirements, what do you mean by that ?

**Comment by ToeiRei** [comment]
composer for example :)

**Comment by gaillota** [comment]
Giving that this repository uses Symfony 2, it's pretty obvious that you need Composer. But I get the idea. I'll update the README asap.
